### ISSUE TITLE
compile error on mac 10.15.6

### ISSUE THREAD

**Issue by planar-pathways** [timredfern/pd_helios#2]
just found this. looks amazing! trying to build on mac and running into the following:
```

ls: ../pure-data/src//m_pd.h: No such file or directory
++++ info: using Makefile.pdlibbuilder version 0.5.1
src/pd-lib-builder/Makefile.pdlibbuilder:759: Where is Pd API m_pd.h? Do 'make help' for info.
++++ info: making target all in lib helios
++++ info: evaluating implicit prerequisites in lib helios.....
src/helios.cpp:12:10: fatal error: 'm_pd.h' file not found
#include "m_pd.h"
         ^~~~~~~~
1 error generated.
src/pd-lib-builder/Makefile.pdlibbuilder:974: *** missing separator.  Stop.

```
any pointers? THANKS!!

**Comment by timredfern** [comment]
sorry, only just spotted this. works for me on 10.15.7

did you get the pure data source?

The ful list of commands would be:

`git clone git@github.com:timredfern/pd_helios.git`
`git clone https://github.com/pure-data/pure-data`
`cd pd_helios`
`make PDINCLUDEDIR=../pure-data/src/`

**Comment by planar-pathways** [comment]
Hey! Cant remember how but i made it work in the end, yes. Thanks for this!
Great work!

**Comment by timredfern** [comment]
Thanks. Would love to see what you have done with it!

**Comment by planar-pathways** [comment]
will send video when done!

Roc Jiménez de Cisneros
http://vivapunani.org
@_roc

Ξ Ξ Ξ Ξ Ξ Ξ Ξ Ξ Ξ Ξ Ξ
